# Generated by Django 4.1.7 on 2023-02-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_remove_building_lease_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='photo_build',
            field=models.FileField(null=True, upload_to='', verbose_name='photo'),
        ),
    ]
